site_name: Compiladores
site_description: Documentação do projeto de Compiladores

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - Documentação:
      - Relatório de Desenvolvimento: documentacao/relatoriodesenvolvimento.md
      - Especificações do Compilador: documentacao/specs.md
  - Sprints:
      - Índice de Sprints: documentacao/sprints/index.md
      - Sprint 1: documentacao/sprints/sprint1.md
      - Sprint 2: documentacao/sprints/sprint2.md
